### ISSUE TITLE
Add examples folder with example projects 

### ISSUE THREAD

**Issue by tribou** [chantastic/minions.css#14]
In order to help newcomers, it would be nice to see some basic projects (with preferably a React one) to show how to start using minions.css.

Or perhaps links to other projects in the README?

**Comment by chantastic** [comment]
@tribou thanks for the feedback! yah, it's been high on my list of priorities to show some demos. right now, it's not friendly at all.

Which examples do you think would be most helpful? These are the ones I had in my mind:
- Trello "boards" page
- Trello "board" page
- Holy Grail Layout
- Slack channel view
- Medium post
- Photo grid
- Instagram profile page

I'm totally open to other ideas. I feel like those are pretty common ones.

**Comment by tribou** [comment]
I would be curious to see it used to create a responsive grid-like layout, so the Holy Grail Layout or a basic photo grid would accomplish that.

However, for the behind-the-scenes/plumbing, I'd like to see it bundled with Webpack and how you prefer to use it in a React component.

**Comment by rudin** [comment]
+1 for that. A sample project showing how to bundle/use this with Webpack+React would be great!

**Comment by chantastic** [comment]
Closing this just to keep things tidy.

I'm putting a little more attention on education at learnreact.com and am planning a course on using Atom CSS style classes in React.

Thanks for the fedback!
