### ISSUE TITLE
Add version for bower

### ISSUE THREAD

**Issue by danielma** [chantastic/minions.css#2]
We would like to use minions.css in one of our projects through https://rails-assets.org/ but in order to do so, we need minions.css to have at least one version published for bower. Would you mind creating a git tag so it works properly?

**Comment by chantastic** [comment]
@danielma published tag v.0.0.1. `bower info minions.css` seemed to pick it up. let me know if you have any issues.

the whole thing is pretty experimental. all of the breakpoints in the lib are hard-coded and are different than those that we typically use at PCO. for that reason, there's a good chance that you'll end up vendoring these assets anyway.

**Comment by danielma** [comment]
@chantastic thank you! We're not using any of the breakpoint classes yet, so it may prove useful for now. Thanks for the additional info though
