### ISSUE TITLE
kill 025 and 05

### ISSUE THREAD

**Issue by chantastic** [chantastic/minions.css#29]
i hate these classes.

i'm thinking `h`alf and `q`uarter `t`hree-quarter.

example:

`p-hr` `p-qe` `p-tr`

**Comment by jessejanderson** [comment]
:thumbsdown:

**Comment by chantastic** [comment]
there's a problem in that they don't really make any sense the way that they are. they should be `p-0.25r` and `p-0.5r`.

currently, there's no consistent way to add values between full rems. with the `025` pattern, `25r` should be `2.5rem`. but it's ambiguous because it could just as easily mean `25rem`.

**Comment by chantastic** [comment]
what i don't want is to go the rout of other frameworks where the number is a scale value. i can't wrap my head around `1` meaning `0.5rem`

**Comment by chantastic** [comment]
If it stays a decimal, it will be updated to show the `.`, which i feel is cumbersome.

**Comment by jessejanderson** [comment]
I think that the leading `0` is clear enough in this minimal verbiage context to imply a decimal.

I don't think the `25r` confusion is real — a rule of "it is what it says it is, unless there's a leading 0" is not a very confusing rule.

The proposed `h` `q` `t` are far more difficult to parse on reading. They also make less sense since we use rems with a 1rem = 10px.

"Half" isn't what I'm thinking when I do `m-05r`... I'm not thinking "half of 1 rem (aka half of 10px)", I'm thinking ".5 rems which is 5px".

**Comment by jessejanderson** [comment]
Not to mention `h`alf, `q`uarter, `t`hree-quarter, even _if_ it's parsed correctly, sounds like a percentage value.

If you know what the letters stand for, `p-hr` looks like `padding: 50%rem`

I think this is a solution wrought with issues, searching for a problem.

Vs. an extremely easy "leading zero means a decimal" rule.

If you're trying to fix something - I recommend changing `background-color` from `gc-` to `bgc-`. ;)

**Comment by chantastic** [comment]
haha!

**Comment by chantastic** [comment]
i think that how the rules are extended is part of the value of this solution over others.

`25r` reads like `25rem` to me. And needing something to be `2.5rem` (or similar) isn't uncommon. the solution isn't clearly extensible.

contrast that to the luminance scale, which is nicely extensible. ships with `c-l.1` and `c-l.2` but you could add `c-l.15` app-side and know what you're gonna get.

**Comment by chantastic** [comment]
The benefit of thinking about things values in terms of units (one, half, quarter) is that they transcend one application's single unit of measurement. For example, I never think in base-10 when I'm working on this. I always think in base-16, base-20, and base-12. I still think it's an abomination that we scale down `rem` to `10px`

**Comment by chantastic** [comment]
Resolved by 985e272af0d04d74c52421d31655f3a1d8f79d90 and 228ac3477aa87454c6ca84548b023448604dea14
